#!/bin/sh

# Add your github username
USER_NAME=
# Add your github access token
ACCESS_TOKEN=

GITHUB_URL=https://api.github.com
ISSUE_NUM=0
COMMENT=$2

getOrgRepo() {
  MYVAR=$(exec git remote -v | grep origin | grep push)
  NAME=${MYVAR%.git*}
  NAME=${NAME#*//github.com}
  echo $NAME
}
ORG_REPO=$(getOrgRepo)

# gish get <issue_num>
if [ $1 = get ]
then
  re='^[0-9]+$'
  if [[ $2 =~ $re ]]
  then
    ISSUE_NUM=$2
    curl -u $USER_NAME:$ACCESS_TOKEN $GITHUB_URL/repos$ORG_REPO/issues/$ISSUE_NUM | grep 'body\|login'
    curl -u $USER_NAME:$ACCESS_TOKEN $GITHUB_URL/repos$ORG_REPO/issues/$ISSUE_NUM/comments | grep 'body\|login'

  # gish get
  else
    curl -u $USER_NAME:$ACCESS_TOKEN $GITHUB_URL/repos$ORG_REPO/issues | grep '"number"\|"title"\|"comments"'
  fi
fi

# gish comment <issue_num> <comment>
if [ $1 = comment ]
then
  ISSUE_NUM=$2
  COMMENT=$3
  curl -d "{ \"body\": \"${COMMENT}\" }" -u $USER_NAME:$ACCESS_TOKEN $GITHUB_URL/repos$ORG_REPO/issues/$ISSUE_NUM/comments
fi

# gish browser
if [ $1 = browser ]
then
  ISSUE_NUM=$(cat /tmp/gish${ORG_REPO}/gish.dat)
  open https://github.com$ORG_REPO/issues/$ISSUE_NUM
fi


# creating an issue
if [ $1 = create ]
then
  TITLE=$2
  DESC=$3
  # Create the issue on github
  curl -d "{\"title\": \"$TITLE\", \"body\": \"$DESC\" }" -u $USER_NAME:$ACCESS_TOKEN $GITHUB_URL/repos$ORG_REPO/issues \
    | grep "number\|title"
fi


# starting and finishing an issue
if [ $1 = start ]
then
  ISSUE_NUM=$2
  # if we don't have a file, start at zero
  if [ ! -f "/tmp/gish$ORG_REPO/gish.dat" ]
  # Should check if there is already an issue?
  then
    mkdir -p "/tmp/gish$ORG_REPO}"
    touch /tmp$ORG_REPO/gish.dat
  fi

  # Add assignent on github
  curl -d "{\"assignees\": [ \"$USER_NAME\" ] }" -u $USER_NAME:$ACCESS_TOKEN $GITHUB_URL/repos$ORG_REPO/issues/$ISSUE_NUM \
    | grep "title\|body"

  # show it to the user
  echo "You are now assigned to issue number: ${ISSUE_NUM}"
  echo "to open in the browser, type 'gish browser'"
  echo "to view issue, type 'gish get ${ISSUE_NUM}'"
  echo "to end the issue, type 'gish end'"

  # and save it for next time
  echo "${ISSUE_NUM}" > /tmp/gish$ORG_REPO/gish.dat
fi

if [ $1 = end ]
then
  if [ ! -f "/tmp/gish${ORG_REPO}/gish.dat" ]
  then
    echo 'No issue has started'
    return 1
  else
    ISSUE_NUM=$(cat /tmp/gish${ORG_REPO}/gish.dat)

    # Remove assignent on github
    curl -d "{\"assignees\": [] }" -u $USER_NAME:$ACCESS_TOKEN $GITHUB_URL/repos$ORG_REPO/issues/$ISSUE_NUM
    echo 'finishing issue number '$ISSUE_NUM
    echo "" > /tmp/gish${ORG_REPO}/gish.dat
  fi
fi


if [ $1 = repo ]
then
  echo "________ inside function __________"
  curl -d "{\"name\": \"$2\" }" -u $USER_NAME:$ACCESS_TOKEN $GITHUB_URL/user/repos \
  | grep "git_url"
  echo "Now run…"
  echo "git remote add origin https://github.com/JMurphyWeb/$2.git"
  echo "git push -u origin master"
fi


if [ $1 = "-h" ]
then
  echo "gish repo <repo-name>                      ---   Create a new repo with given name"
  echo "gish create \"<title>\" \"<description>\"      ---   Create a new repo with given name"
  echo "gish get                                   ---   Get list of issues"
  echo "gish get <issue_number>                    ---   Get description and comments of a given issue"
  echo "gish start <issue_number>                  ---   Starts an issue (assigns you)"
  echo "gish comment <issue_number> \"<comment>\"    ---   Adds a comment to an issue"
  echo "gish browser                               ---   Opens the current issue in the browser"
  echo "gish end                                   ---   Remove assignment of the current issue"
fi

# POST NEW ISSUE WITH ASSIGNMENT
# curl -d "{\"assignees\": [ \"JMurphyWeb\" ], \"title\": \"TEST\"}" -u username:token https://api.github.com/repos/JMurphyWeb/gish/issues
